<?php
/**
 * @author Gustavo Dauer <gustavo.dauer@hotmail.com>
 */
/** @var Dauer\GiftMessagePlusFrontendUi\ViewModel\AddConfigurationToAdminArea $viewModel */
$viewModel = $block->getData('gift_plus_view_model');
$script = "window.checkoutConfig = {$viewModel->getGiftMessageConfig()};"
?>

<?php if ($block->canDisplayGiftmessageForm()) : ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $script, false) ?>
    <div id="gift_options_giftmessage" class="giftcard-form giftcard-send-form fieldset admin__fieldset">
        <div class="field admin__field">
            <label class="admin__field-label" for="current_item_giftmessage_sender"><?= $block->escapeHtml(__('From')) ?></label>
            <div class="control admin__field-control">
                <input type="text" class="input-text admin__control-text"
                       name="current_item_giftmessage_sender"
                       id="current_item_giftmessage_sender" />
            </div>
        </div>
        <div class="field admin__field">
            <label class="admin__field-label" for="current_item_giftmessage_recipient"><?= $block->escapeHtml(__('To')) ?></label>
            <div class="control admin__field-control">
                <input type="text"
                       class="input-text admin__control-text"
                       name="current_item_giftmessage_recipient"
                       id="current_item_giftmessage_recipient" />
            </div>
        </div>
        <div class="field admin__field">
            <label class="admin__field-label" for="current_item_giftmessage_message"><?= $block->escapeHtml(__('Message')) ?></label>
            <div class="control admin__field-control">
            <textarea class="textarea admin__control-textarea"
                      cols="15"
                      rows="2"
                      name="current_item_giftmessage_message"
                      id="current_item_giftmessage_message"
                      data-bind="'mageInit': {'wyswigEnabler': {index: 'current_item_giftmessage_message', area: 'adminhtml'}}"
            ></textarea>
            </div>
        </div>
    </div>
<?php endif; ?>
